title: Deutscher Parkourverband e.V.
email: info@parkour-deutschland.de
author: Deutscher Parkourverband e.V.
instagram_username: parkour_deutschland
whatsapp_group: CFBk17YVZ5G7jDn3uGc836
github_username: parkour-de

show_excerpts: true

description: >- # this means to ignore newlines until "baseurl:"
  Das ist die Website des Deutschen Parkourverbands e.V.

# Build settings
theme: minima
